CREATE DATABASE IF NOT EXISTS cs2_case_simulator
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'cs2_app'@'127.0.0.1'
  IDENTIFIED BY 'CHANGE_ME_TO_A_LONG_RANDOM_PASSWORD';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
ON cs2_case_simulator.* TO 'cs2_app'@'127.0.0.1';

FLUSH PRIVILEGES;
